# Generated by Django 4.2.2 on 2023-06-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("currency", models.CharField(max_length=50, unique=True)),
                ("buy", models.DecimalField(decimal_places=4, max_digits=10)),
                ("sell", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
