# Generated by Django 4.2.2 on 2023-06-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyrate",
            name="image",
            field=models.ImageField(default=1, upload_to="media/"),
            preserve_default=False,
        ),
    ]
