# Generated by Django 4.2.2 on 2023-06-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_currencyrate_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyrate",
            name="currency_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
