# Generated by Django 4.2.1 on 2023-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_currencyrate_currency_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ATM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField()),
                ("city", models.CharField()),
                ("address", models.CharField()),
                ("atm_name", models.CharField()),
                ("atm_number", models.CharField()),
            ],
        ),
    ]
