# Generated by Django 4.2.3 on 2023-07-07 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_atm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atm",
            options={"ordering": ("country", "city", "address")},
        ),
    ]
