# Generated by Django 4.2.1 on 2023-05-24 20:01

import datetime
import re

import django.core.validators
from django.db import migrations, models

import user.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("uuid", models.UUIDField(default=user.utils.user_uuid, unique=True)),
                (
                    "first_name",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_username", message="Invalid name.", regex="^[A-Za-zА-Яа-я-]{2,30}$"
                            )
                        ]
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_username", message="Invalid last name.", regex="^[A-Za-zА-Яа-я-]{2,30}$"
                            )
                        ]
                    ),
                ),
                (
                    "passport_id",
                    models.CharField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_passport_number",
                                message="Passport number must must contain uppercase english letters and contain "
                                "between 6 and 20 digits",
                                regex=re.compile("^[A-Z0-9]{6,20}$"),
                            )
                        ],
                    ),
                ),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="Phone number must start with  +  and contain between 10 and 15 digits",
                                regex=re.compile("^\\+\\d{10,15}$"),
                            )
                        ],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Password must contain at least one uppercase letter, one lowercase letter,"
                                " one digit, and one special character",
                                regex=re.compile(
                                    "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&+])[A-Za-z\\d@$!%*?&+]{8,20}$"
                                ),
                            )
                        ]
                    ),
                ),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(fields=("passport_id",), name="unique_passport_id"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(fields=("phone_number",), name="unique_phone_number"),
        ),
    ]
