# Generated by Django 4.2.3 on 2023-07-06 16:11

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_email_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username", message="Invalid name.", regex="^[A-Za-zА-Яа-я\\s\\'-]{2,30}$"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username", message="Invalid last name.", regex="^[A-Za-zА-Яа-я\\s\\'-]{2,30}$"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="passport_id",
            field=models.CharField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_passport_number",
                        message="Passport number must must contain uppercase english letters and contain between "
                        "6 and 20 digits",
                        regex="^[A-Z0-9]{6,20}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Phone number must start with  +  and contain between 11 and 12 digits",
                        regex=re.compile("^\\+\\d{11,12}$"),
                    )
                ],
            ),
        ),
    ]
